  version: "2"


  services:


     web:

        build: ./web

        ports:

          -  "80:80"
          
        volumes:

          -  ./html/:/var/www/html

     db:

       build: ./db

       ports:

         - "30000:3306"

       environment:

          MYSQL_ROOT_PASSWORD: password
